### ISSUE TITLE
Make logs more specific

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/language-postgresql#24]
See https://github.com/OpenFn/language-postgresql/blob/master/src/Adaptor.js#L195 and the related logs.

@lakhassane , what a great opportunity to provide some simple, clear feedback to the user. Same number of words, but less ambiguous:

Before: `'No data found, Skipping insert.'`
After: `'No records provided; skipping insert.'`

For https://github.com/OpenFn/language-postgresql/blob/master/src/Adaptor.js#L386 , maybe: `'No columns provided; skipping insert.'` ? I like "provided" since you're saying to them... "this is what you gave me"

**Comment by lakhassane** [comment]
@taylordowns2000 could you check to see if logs are fine by you before I make the release
