### ISSUE TITLE
New `findValue(...)` helper function

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/language-postgresql#27]
## Background
Inspired by a client's desire to map several many:1 and many:many relationships between postgres tables. See Slack thread for the related conversation: https://openfn.slack.com/archives/C017ELVRSM8/p1616493074002500?thread_ts=1616491089.001300&cid=C017ELVRSM8

## Request
Create a new helper function: 
`findValue('table', 'betterBeUniqueColumn', 'returnColumn', 'searchValue')`

Currently the client would have to write a `sql(...)` query to look-up parent table values to set the foreign key on a new record. [See WCS docs](https://openfn.github.io/ConSoSci/jobs/#3-mapping-m1-relationships-that-frequently-change--executing-sql-queries-to-look-up-existing-data) for an example. 

Rather, ideally the client could replace [L83 in this sample job](https://github.com/OpenFn/ConSoSci/blob/master/vegetation/VegetationClassficationAndTreeMeasurementForm.js#L83) with the below mapping: 
```
topography: findValue(WCSPROGRAMS_VegetationTopography, WCSPROGRAMS_VegetationTopographyID, WCSPROGRAMS_VegetationTopographyID, dataValue('topography')),
```

## Testing
Consider how this will work if placed in `upsert(...)` vs `upsertMany(...)` helpers.

**Comment by lakhassane** [comment]
After few tests, having just something like this works perfectly and we can display the foreign key needed.
```js
alterState(state => {
  return findValue('users', 'first_name', 'id', 'Mamadou')(state;
});
```
However, as discussed `expandReferences` can bring a small trouble since `findValues` is expected to return a `single value` and not a Promise which is the case right now if we run any sql query in it.

The main pattern we want would look like this (and is not working yet)

```js
alterState(state => {
  console.log('Building a mapping');

  const user = {
    name: 'Mamadou',
    address: 'Dakar',
    user_id: state => {
      return findValue('users', 'first_name', 'id', 'Mamadou')(state);
    },
  };

  console.log('user data', user);

  return upsert('table_test', 'id', user)(state);
});
```
I think as soon as we see how to NOT return a promise in findValues this can be done in `2hours`. I'm pushing the draft I just made in a new branch.

**Comment by aleksa-krolls** [comment]
@lakhassane Priority for this is lower than any specific project work, but please start on this when you get the chance today/tomorrow.

**Comment by aleksa-krolls** [comment]
@lakhassane Keep me posted when this is done and on production. On Monday hoping to test it out on some WCS jobs.

**Comment by aleksa-krolls** [comment]
@lakhassane @taylordowns2000 just learned that this `findValue(...)` helper will be needed to be implemented first on `language-mssql`... later on `language-postgresql`. See issue here that I will prioritize in the backlog: https://github.com/OpenFn/language-mssql/issues/17

**Comment by taylordowns2000** [comment]
Noted. Thanks. @lakhassane and @stuartc will be taking a look at this (https://github.com/OpenFn/language-mssql/issues/17) today!
