### ISSUE TITLE
Create functions for `upsert` and `insertMany`

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/language-postgresql#5]
See the `upsert(..)` and `insertMany(...)` helper functions we have implemented for [language-mssql](https://github.com/OpenFn/language-mssql). We need to implement the same for Postgres for WCS ([see example job](https://github.com/OpenFn/wcs/blob/master/bns/survey.js) that leverages these). 

The patterns should be the same, but now Postgres will be the destination system. If you need postgres creds, see LP 'Wildmeat Postgres Transitional DB (WCS)'. 

**Please log hours to "WCS Wildmeat" Toggl project:** https://toggl.com/app/3335160/projects/162933747/team

**Comment by aleksa-krolls** [comment]
@taylordowns2000 here is the requirement for LP changes needed for upcoming WCS jobs.

**Comment by taylordowns2000** [comment]
@lakhassane , we have a pattern for this already built in the `mssql` adaptor (see Aleksa's comment above). to get started, we'll need to make sure you've got a test DB running on your local postgres... will be much easier to do end-to-end testing that way :-)
